env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - extends: .eslintrc.jest.yml
    files:
    - '__tests__/**'
    - '*.spec.js'
    - '*.spec.jsx'
    - '*.spec.ts'
    - '*.spec.tsx'
    - '*.test.js'
    - '*.test.jsx'
    - '*.test.ts'
    - '*.test.tsx'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - react
  - '@typescript-eslint'
root: true
rules:
  prettier/prettier: error
  no-empty:
    - error
    - allowEmptyCatch: true
settings:
  react:
    version: '16.8'
