name: Publish release on push tag

on:
  push:
    tags: 'v*'

jobs:
  call-workflow:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: compulim/workflows/.github/workflows/publish-release.yml@main
    with:
      package-name: use-ref-from
