name: Publish release on push tag

on:
  push:
    tags: 'v*'

jobs:
  build-and-draft:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-version.outputs.tag }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - id: get-version
        name: Get version
        run: |
          echo tag=`echo ${{ github.ref }} | awk '{ sub(/^refs\/tags\//, ""); print; }'` > $GITHUB_OUTPUT
          echo version=`cat package.json | jq -r '.version'` >> $GITHUB_OUTPUT
      - name: Check version number
        if: ${{ contains(steps.get-version.outputs.version, '-') }}
        run: |
          echo Version number must not be a prerelease.
          exit 1
      - name: Propagate versions
        run: |
          cd packages/use-ref-from
          npm version --no-git-tag-version ${{ steps.get-version.outputs.version }}
      - run: npm clean-install
      - run: npm run build --if-present
      - name: Run npm pack
        run: |
          cd packages/use-ref-from
          npm pack
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: tarball
          path: packages/use-ref-from/*.tgz
      - name: Draft a new release
        run: gh release create ${{ steps.get-version.outputs.tag }} ./packages/use-ref-from/*.tgz --draft --notes-file ./CHANGELOG.md
        env:
          GH_TOKEN: ${{ github.token }}

  publish-package:
    environment: production
    needs: build-and-draft
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download tarball artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: tarball
      - run: npm publish `ls ./*.tgz`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-release:
    needs:
      - build-and-draft
      - publish-package
    runs-on: ubuntu-latest

    steps:
      - name: Publish release
        run: gh release edit ${{ needs.build-and-draft.outputs.tag }} --draft=false --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
