name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    strategy:
      matrix:
        react-version: [current, 16, 17, 18]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      package-name: use-ref-from
      react-version: ${{ matrix.react-version }}
      skip-integration-test: false
